# Generated by Django 3.1.1 on 2020-11-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeskripsiDiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_diri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hobi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kemampuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kemampuan', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekolah', models.CharField(max_length=30)),
                ('tahun_mulai', models.CharField(max_length=10)),
                ('tahun_selesai', models.CharField(max_length=10)),
                ('jurusan', models.CharField(max_length=30, null=True)),
                ('jenjang', models.CharField(max_length=30, null=True)),
                ('deskripsi_pendidikan', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertifikat', models.CharField(max_length=50)),
                ('scan', models.ImageField(upload_to='scan/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=15, null=True)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengalaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengalaman', models.TextField()),
                ('bagian', models.CharField(max_length=30)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.kategori')),
            ],
        ),
    ]
